[package]
name = "pstor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.4.1"
uuid = { version = "1.4.1", features = ["v4"] }
strum = "0.24.1"
strum_macros = "0.24.3"
serde_json = "1.0.107"
tokio = { version = "1.32.0", features = [ "full" ] }
snafu = "0.7.5"
etcd-client = "0.10.4"
serde = { version = "1.0.188", features = ["derive"] }
async-trait = "0.1.73"
dyn-clonable = "0.9.0"
rand = "0.8.5"
tonic = "0.8.3"
tracing = "0.1.37"
parking_lot = "0.12.1"

# Utils dependencies
platform = { path = "../platform" }

[dev-dependencies]
composer = { path = "../dependencies/composer" }
tokio = { version = "1.32.0", features = [ "full" ] }
