name: Release Artifacts
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - 'release-**'
      - 'release/**'
      - 'hotfix-v**'

jobs:
#   kubectl-plugin:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         include:
#           - os: macos-latest
#             target: apple-darwin
#           - os: ubuntu-latest
#             target: linux-musl
# # TODO: not currently working
# #          - os: ubuntu-latest
# #            target: windows-gnu
# #            suffix: .exe
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           submodules: recursive
#       - uses: cachix/install-nix-action@v17
#         with:
#           nix_path: nixpkgs=channel:nixos
#       - run: nix-build -A utils.release.${{ matrix.target }}.kubectl-plugin
#       - uses: actions/upload-artifact@v3
#         with:
#           name: kubectl-mayastor-${{ matrix.target }}
#           path: ./result/bin/kubectl-mayastor${{ matrix.suffix }}
#           if-no-files-found: error
          
  arm64_job:
    runs-on: ubuntu-latest
    name: Build on ubuntu-22.04 arm64
    steps:
      - uses: actions/checkout@v3
        with:
           submodules: recursive
      - uses: uraimo/run-on-arch-action@v2.2.0
        with:
          arch: aarch64
          distro: ubuntu22.04
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos
      - run: nix-build -A utils.release.linux-musl.kubectl-plugin
      - uses: actions/upload-artifact@v3
        with:
          name: kubectl-mayastor-linux-musl
          path: ./result/bin/kubectl-mayastor
          if-no-files-found: error
