[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
tracing-opentelemetry = "0.17.4"
opentelemetry = { version = "0.17.0", features = ["rt-tokio-current-thread"] }
opentelemetry-jaeger = { version = "0.16.0", features = ["rt-tokio-current-thread"] }
version-info = { path = "../dependencies/version-info", default-features = false }
git-version-macro = { path = "../dependencies/rust-git-version/git-version-macro" }
